# Generated by Django 4.1.7 on 2023-03-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='generos',
        ),
    ]
