# Generated by Django 4.1.7 on 2023-03-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentasApp', '0002_remove_usuarios_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='generos',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='VentasApp.generos'),
        ),
    ]
